### ISSUE TITLE
Does not compile on windows.

### ISSUE THREAD

**Issue by maikonaraujo** [containers/oci-spec-rs#181] opened 2024-07-03 22:54 UTC
Fails to build with the following errors:

 
151               typ: PosixRlimitType::RlimitNofile,
                                      ^^^^^^^^^^^^ variant or associated item not found in `PosixRlimitType`

191 | pub enum PosixRlimitType {
   ------------------------ variant or associated item `RlimitNofile` not found for this enum

191 | pub enum PosixRlimitType {
  ------------------------ variant or associated item `RlimitCpu` not found for this enum

265       Self::RlimitCpu
               ^^^^^^^^^ variant or associated item not found in `PosixRlimitType`

**Comment by saschagrunert** [comment] 2024-07-04 06:47
That's a duplicate of https://github.com/containers/oci-spec-rs/issues/179, we're working on a new release to fix that issue.

**Closed** 2024-07-04 06:48 UTC
